import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-app.js';
import {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-auth.js';
import {getFirestore,doc,setDoc,collection,addDoc,query,where,getDocs} from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js';
const config={apiKey:'AIzaSyB9TlSjbQ7kSAyySiEmcYnUH1DuYuSNzvE',authDomain:'avr-creation.firebaseapp.com',projectId:'avr-creation',storageBucket:'avr-creation.firebasestorage.app',messagingSenderId:'532572942663',appId:'1:532572942663:web:c50d1d53274bc01cf7dc62'};
const auth=getAuth(initializeApp(config)),db=getFirestore();const ADMIN_EMAIL='raghunaikskp9686@gmail.com';let registering=false,currentUser=null;
const setMode=register=>{registering=register;authTitle.textContent=register?'ಗ್ರಾಹಕ ನೋಂದಣಿ':'ಗ್ರಾಹಕ ಲಾಗಿನ್';authIntro.textContent=register?'ಮೊಬೈಲ್ ನಂಬರ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ ಖಾತೆ ತೆರೆಯಿರಿ.':'ಮೊಬೈಲ್ ನಂಬರ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ ಲಾಗಿನ್ ಮಾಡಿ.';authSubmit.textContent=register?'ಖಾತೆ ತೆರೆಯಿರಿ':'ಲಾಗಿನ್';authSwitch.textContent=register?'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ':'ಹೊಸ ಗ್ರಾಹಕರೇ? ನೋಂದಣಿ ಮಾಡಿ';authError.hidden=true};
authSwitch.onclick=()=>setMode(!registering);
authForm.addEventListener('submit',async e=>{e.preventDefault();authError.hidden=true;try{const mobile=authMobile.value.trim();if(!/^\d{10}$/.test(mobile))throw new Error('ಸರಿಯಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ನಂಬರ್ ಬರೆಯಿರಿ.');const internalEmail=`m${mobile}@avrcreation.firebaseapp.com`;if(registering){const c=await createUserWithEmailAndPassword(auth,internalEmail,authPassword.value);await setDoc(doc(db,'customers',c.user.uid),{mobile,createdAt:new Date().toISOString()});}else await signInWithEmailAndPassword(auth,internalEmail,authPassword.value);}catch(err){authError.textContent=err.message.replace('Firebase: ','');authError.hidden=false}});
onAuthStateChanged(auth,user=>{currentUser=user;if(user){authView.hidden=true;customerView.hidden=false;adminView.hidden=true;customerGreeting.textContent=`ನಮಸ್ಕಾರ, ${user.displayName||'ಗ್ರಾಹಕರೇ'}`;loadRequests()}else{authView.hidden=false;customerView.hidden=true;adminView.hidden=true;setMode(false)}});
requestForm.addEventListener('submit',async e=>{e.preventDefault();try{await addDoc(collection(db,'requests'),{uid:currentUser.uid,service:serviceSelect.value,note:requestNote.value.trim(),status:'ಹೊಸ ವಿನಂತಿ',createdAt:new Date().toISOString()});requestNote.value='';requestResult.textContent='ನಿಮ್ಮ ವಿನಂತಿ ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.';requestResult.hidden=false;loadRequests()}catch(err){requestResult.textContent='ವಿನಂತಿ ಕಳುಹಿಸಲು ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';requestResult.hidden=false}});
async function loadRequests(){const records=await getDocs(query(collection(db,'requests'),where('uid','==',currentUser.uid)));const items=records.docs.map(d=>d.data()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));requestHistory.innerHTML=items.length?items.map(r=>`<article class="request"><strong>${r.service}</strong><span>${r.status}</span><small>${r.note||''}</small></article>`).join(''):'<p class="empty">ಇನ್ನೂ ಯಾವುದೇ ವಿನಂತಿ ಇಲ್ಲ.</p>'}
logoutButton.onclick=()=>signOut(auth);
window.openAdmin=async()=>{try{if(!currentUser){const email=prompt('Admin email ID ಬರೆಯಿರಿ:');const password=prompt('Admin password ಬರೆಯಿರಿ:');if(!email||!password)return;await signInWithEmailAndPassword(auth,email,password)}if(!currentUser||currentUser.email!==ADMIN_EMAIL){await signOut(auth);alert('ಈ emailಗೆ admin access ಇಲ್ಲ.');return}authView.hidden=true;customerView.hidden=true;adminView.hidden=false;const records=await getDocs(collection(db,'requests'));const items=records.docs.map(d=>d.data()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));adminRequestList.innerHTML=items.length?items.map(r=>`<article class="request"><strong>${r.service}</strong><span>${r.status}</span><small>${r.note||'ಯಾವುದೇ ವಿವರ ಇಲ್ಲ'}</small><time>${r.createdAt}</time></article>`).join(''):'<p class="empty">ಇನ್ನೂ customer requests ಬಂದಿಲ್ಲ.</p>'}catch{alert('Admin email ಅಥವಾ password ಸರಿಯಿಲ್ಲ.')}};
adminLogoutButton.onclick=()=>signOut(auth);
