import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-app.js';
import {getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut,updateProfile} from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-auth.js';
import {getFirestore,doc,setDoc,collection,addDoc,query,where,getDocs} from 'https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js';
const config={apiKey:'AIzaSyB9TlSjbQ7kSAyySiEmcYnUH1DuYuSNzvE',authDomain:'avr-creation.firebaseapp.com',projectId:'avr-creation',storageBucket:'avr-creation.firebasestorage.app',messagingSenderId:'532572942663',appId:'1:532572942663:web:c50d1d53274bc01cf7dc62'};
const auth=getAuth(initializeApp(config)),db=getFirestore();let registering=false,currentUser=null;
const setMode=register=>{registering=register;authTitle.textContent=register?'ಗ್ರಾಹಕ ನೋಂದಣಿ':'ಗ್ರಾಹಕ ಲಾಗಿನ್';authIntro.textContent=register?'ಹೊಸ ಖಾತೆ ತೆರೆದು ಸೇವೆಗೆ ವಿನಂತಿಸಿ.':'ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ.';nameLabel.hidden=!register;mobileLabel.hidden=!register;authSubmit.textContent=register?'ಖಾತೆ ತೆರೆಯಿರಿ':'ಲಾಗಿನ್';authSwitch.textContent=register?'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ':'ಹೊಸ ಗ್ರಾಹಕರೇ? ನೋಂದಣಿ ಮಾಡಿ';authError.hidden=true};
authSwitch.onclick=()=>setMode(!registering);
authForm.addEventListener('submit',async e=>{e.preventDefault();authError.hidden=true;try{if(registering){if(!authName.value.trim()||!authMobile.value.trim())throw new Error('ಹೆಸರು ಮತ್ತು ಮೊಬೈಲ್ ನಂಬರ್ ಬರೆಯಿರಿ.');const c=await createUserWithEmailAndPassword(auth,authEmail.value,authPassword.value);await updateProfile(c.user,{displayName:authName.value.trim()});await setDoc(doc(db,'customers',c.user.uid),{name:authName.value.trim(),mobile:authMobile.value.trim(),email:authEmail.value,createdAt:new Date().toISOString()});}else await signInWithEmailAndPassword(auth,authEmail.value,authPassword.value);}catch(err){authError.textContent=err.message.replace('Firebase: ','');authError.hidden=false}});
onAuthStateChanged(auth,user=>{currentUser=user;if(user){authView.hidden=true;customerView.hidden=false;customerGreeting.textContent=`ನಮಸ್ಕಾರ, ${user.displayName||'ಗ್ರಾಹಕರೇ'}`;loadRequests()}else{authView.hidden=false;customerView.hidden=true;setMode(false)}});
requestForm.addEventListener('submit',async e=>{e.preventDefault();try{await addDoc(collection(db,'requests'),{uid:currentUser.uid,service:serviceSelect.value,note:requestNote.value.trim(),status:'ಹೊಸ ವಿನಂತಿ',createdAt:new Date().toISOString()});requestNote.value='';requestResult.textContent='ನಿಮ್ಮ ವಿನಂತಿ ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.';requestResult.hidden=false;loadRequests()}catch(err){requestResult.textContent='ವಿನಂತಿ ಕಳುಹಿಸಲು ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';requestResult.hidden=false}});
async function loadRequests(){const records=await getDocs(query(collection(db,'requests'),where('uid','==',currentUser.uid)));const items=records.docs.map(d=>d.data()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));requestHistory.innerHTML=items.length?items.map(r=>`<article class="request"><strong>${r.service}</strong><span>${r.status}</span><small>${r.note||''}</small></article>`).join(''):'<p class="empty">ಇನ್ನೂ ಯಾವುದೇ ವಿನಂತಿ ಇಲ್ಲ.</p>'}
logoutButton.onclick=()=>signOut(auth);
