const ADMIN_MOBILE="8310049524",ADMIN_PASSWORD="1234";
const SERVICES=[
["📄","Ration Card PDF - OTP",20],["📄","Ration Card PDF - Without OTP",25],
["🪪","Aadhaar / e-KYC Assistance",30],["🧾","Certificate / Document Service",30],
["🏦","Banking Form Assistance",30],["🖨️","Print / Download Service",10],
["🔎","QR Scanner Service",10],["📑","Other Online Service",40]
];
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
let users=get("rcc_users",[]),requests=get("rcc_requests",[]),recharge=get("rcc_recharge",[]);
let session=get("rcc_session",null);
function save(){localStorage.setItem("rcc_users",JSON.stringify(users));localStorage.setItem("rcc_requests",JSON.stringify(requests));localStorage.setItem("rcc_recharge",JSON.stringify(recharge))}
function setSession(x){session=x;localStorage.setItem("rcc_session",JSON.stringify(x))}
function logout(){session=null;localStorage.removeItem("rcc_session");location.href="index.html"}
function renderCustomer(){
const a=document.getElementById("app");
if(!session){a.innerHTML=`<div class="wrap login"><div class="card"><h2>👤 Customer Login</h2><input id="m" placeholder="10 digit mobile"><input id="p" type="password" placeholder="Password"><button class="blue" onclick="custLogin()">Login</button><hr><h3>New Customer</h3><input id="n" placeholder="Name"><input id="nm" placeholder="Mobile"><input id="np" type="password" placeholder="Password"><button class="green" onclick="register()">Register</button><p><a href="admin.html">⚙️ Admin Login</a> • <a href="qr-scanner.html">📷 QR Scanner</a></p></div></div>`;return}
const u=users.find(x=>x.mobile===session.mobile);if(!u){logout();return}
a.innerHTML=`<div class="wrap"><div class="card"><h2>Hi ${esc(u.name)} 👋</h2><p>Wallet Balance</p><div class="amount">₹${u.wallet||0}</div><button class="green" onclick="showRecharge()">➕ Add Wallet</button> <button class="gray" onclick="logout()">Logout</button></div><div class="card"><h2>Services</h2><div class="grid">${SERVICES.map((s,i)=>`<div class="card service"><div class="icon">${s[0]}</div><h3>${s[1]}</h3><p>Fee ₹${s[2]}</p><button class="blue" onclick="applyService(${i})">Apply</button></div>`).join("")}</div></div><div class="card"><h2>My Requests</h2>${requests.filter(r=>r.mobile===u.mobile).reverse().map(r=>`<p><b>${esc(r.service)}</b> — ₹${r.fee} — <span class="status">${r.status}</span></p>`).join("")||"No requests yet."}</div></div>`;
}
function register(){const n=document.getElementById("n").value.trim(),m=document.getElementById("nm").value.trim(),p=document.getElementById("np").value;if(!n||!/^[0-9]{10}$/.test(m)||!p)return alert("Name, 10 digit mobile and password ಹಾಕಿ.");if(users.some(x=>x.mobile===m))return alert("Mobile already registered.");users.push({name:n,mobile:m,password:p,wallet:0});save();alert("Registration successful.");renderCustomer()}
function custLogin(){const m=document.getElementById("m").value.trim(),p=document.getElementById("p").value,u=users.find(x=>x.mobile===m&&x.password===p);if(!u)return alert("Login failed");setSession({mobile:u.mobile,admin:false});renderCustomer()}
function showRecharge(){document.getElementById("app").innerHTML=`<div class="wrap"><div class="card"><h2>➕ Add Wallet</h2><p class="note">Admin payment QR scan ಮಾಡಿ. Payment ಆದ ನಂತರ UTR/Reference submit ಮಾಡಿ. Admin approve ಮಾಡಿದ ಮೇಲೆ ಮಾತ್ರ wallet credit ಆಗುತ್ತದೆ.</p><div class="qrbox"><h3>Scan & Pay</h3><img src="payment-qr.jpg" alt="Admin payment QR"></div><input id="ra" type="number" min="1" placeholder="Amount ₹"><input id="utr" placeholder="UTR / Transaction Reference"><button class="green" onclick="sendRecharge()">Submit Recharge Request</button> <button class="gray" onclick="renderCustomer()">Back</button></div></div>`}
function sendRecharge(){const u=users.find(x=>x.mobile===session.mobile),amount=Number(document.getElementById("ra").value),utr=document.getElementById("utr").value.trim();if(!amount||!utr)return alert("Amount ಮತ್ತು UTR ಹಾಕಿ.");recharge.push({id:Date.now(),mobile:u.mobile,name:u.name,amount,utr,status:"Pending",created:new Date().toLocaleString()});save();alert("Recharge request Adminಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.");renderCustomer()}
function applyService(i){const u=users.find(x=>x.mobile===session.mobile),s=SERVICES[i];if((u.wallet||0)<s[2])return alert("Wallet balance ಸಾಕಾಗುವುದಿಲ್ಲ.");requests.push({id:Date.now(),mobile:u.mobile,name:u.name,service:s[1],fee:s[2],status:"Pending",created:new Date().toLocaleString()});save();alert("Service request submitted. Admin complete ಮಾಡಿದಾಗ amount deduct ಆಗುತ್ತದೆ.");renderCustomer()}
function renderAdmin(){const a=document.getElementById("app");if(!session?.admin){a.innerHTML=`<div class="wrap login"><div class="card"><h2>⚙️ Admin Login</h2><input id="am" inputmode="numeric" placeholder="Admin Mobile"><input id="ap" type="password" placeholder="Admin Password"><button class="blue" onclick="adminLogin()">Admin Login</button><p><a href="index.html">← Customer</a></p></div></div>`;return}const received=recharge.filter(x=>x.status==="Approved").reduce((sum,x)=>sum+Number(x.amount),0);a.innerHTML=`<div class="wrap"><div class="card"><h2>⚙️ Admin Dashboard</h2><p>💰 <b>Admin Received / Wallet:</b> ₹${received}</p><button class="red" onclick="logout()">Logout</button></div><div class="card"><h2>💰 Recharge Requests</h2>${recharge.slice().reverse().map(r=>`<div class="card"><b>${esc(r.name)}</b> • ${r.mobile}<br>Amount: <b>₹${r.amount}</b> • UTR: ${esc(r.utr)}<br>Status: ${r.status}${r.status==="Pending"?`<br><button class="green" onclick="approve(${r.id})">✅ Approve & Credit</button> <button class="red" onclick="reject(${r.id})">Reject</button>`:""}</div>`).join("")||"No recharge requests."}</div><div class="card"><h2>📋 Service Requests</h2>${requests.slice().reverse().map(r=>`<div class="card"><b>${esc(r.name)}</b> • ${r.mobile}<br>${esc(r.service)} — ₹${r.fee}<br>Status: ${r.status}${r.status==="Pending"?`<br><button class="green" onclick="complete(${r.id})">Complete & Deduct</button> <button class="red" onclick="rejectReq(${r.id})">Reject</button>`:""}</div>`).join("")||"No requests."}</div></div>`}
function adminLogin(){const m=document.getElementById("am").value.trim(),p=document.getElementById("ap").value;if(m===ADMIN_MOBILE&&p===ADMIN_PASSWORD){setSession({admin:true,mobile:m});renderAdmin()}else alert("Admin mobile/password ತಪ್ಪಾಗಿದೆ.")}
function approve(id){const r=recharge.find(x=>x.id===id),u=users.find(x=>x.mobile===r?.mobile);if(!r||r.status!=="Pending"||!u)return;u.wallet=Number(u.wallet||0)+Number(r.amount);r.status="Approved";r.approved=new Date().toLocaleString();save();renderAdmin();alert("₹"+r.amount+" customer walletಗೆ credit ಆಯಿತು.")}
function reject(id){const r=recharge.find(x=>x.id===id);if(r){r.status="Rejected";save();renderAdmin()}}
function complete(id){const r=requests.find(x=>x.id===id),u=users.find(x=>x.mobile===r?.mobile);if(!r||r.status!=="Pending"||!u)return;if(Number(u.wallet||0)<Number(r.fee))return alert("Customer wallet balance ಕಡಿಮೆ.");u.wallet-=Number(r.fee);r.status="Completed";save();renderAdmin()}
function rejectReq(id){const r=requests.find(x=>x.id===id);if(r){r.status="Rejected";save();renderAdmin()}}
function renderScanner(){document.getElementById("app").innerHTML=`<div class="wrap"><div class="card"><h2>📷 QR Payment Scanner</h2><p class="note">Customer wallet Add Moneyಗೆ Admin payment QR. Customer scan → payment → UTR submit → Admin approve → customer wallet credit.</p><div class="qrbox"><img src="payment-qr.jpg" alt="Admin payment QR"><h3>Scan to Pay</h3></div><p><a href="index.html">Customer</a> • <a href="admin.html">Admin</a></p></div></div>`}
function esc(x){return String(x||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
